version: "3.8"
services:
  joomla_reverse_proxy_service:
    build: .
    image: joomla_reverse_proxy_image
    container_name: joomla_reverse_proxy
    ports:
      - "80:80"
    networks:
      - joomla_net
    depends_on:
      - joomla_nginx_service
      - joomla_apache_service
      - joomla_db_admin_service

  joomla_nginx_service:
    build:
      context: ./nginx-joomla
      dockerfile: NginxJoomla.Dockerfile
    image: joomla_nginx_image
    container_name: joomla_nginx
    networks:
      - joomla_net
    depends_on:
      - joomla_mysql_service

  joomla_apache_service:
    build:
      context: ./apache-joomla
      dockerfile: ApacheJoomla.Dockerfile
    image: joomla_apache_image
    container_name: joomla_apache
    networks:
      - joomla_net
    depends_on:
      - joomla_mysql_service

  joomla_db_admin_service:
    build:
      context: ./php-my-admin
      dockerfile: PhpMyAdmin.Dockerfile
    image: joomla_db_admin_image
    container_name: joomla_db_admin
    environment:
      # You should put here a random 32 character string
      # You can use `openssl rand -hex 16`
      - PHP_BLOWFISH_SECRET=0ef409bb8aef25332c3430354d804dc4
      - PHP_DB_HOST=joomla_mysql_service
    networks:
      - joomla_net
    depends_on:
      - joomla_mysql_service

  joomla_mysql_service:
    image: mysql:8.0.17
    container_name: joomla_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=joomla
    volumes:
      - joomla_data:/var/lib/mysql
    networks:
      - joomla_net

networks:
  joomla_net:

volumes:
  joomla_data:
